spring.application.name=evento

server.port=8085
# Conexión a DB Pacientes
spring.datasource.url=jdbc:mysql://localhost:3306/db_evento?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

