spring.application.name=service-reservas
server.port=8083
# Conexión a DB
spring.datasource.url=jdbc:mysql://localhost:3306/db_reservas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ruta donde se generará el JSON de la documentación
springdoc.api-docs.path=/reservas/v3/api-docs
# Ruta de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html